#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1149412984
ios_app_country                           : us                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CardioBot
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your Apple Watch measures your heart rate every 4 minutes during the day. With CardioBot, you can easily understand the data captured by the Apple Watch so you can improve your lifestyle and discover notable patterns.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Majid Jabrayilov
your_link                                 : https://mecid.github.io
your_city                                 : Baku
email_address                             : cmecid@gmail.com
facebook_username                         : majid.jabrayilov                                          
instagram_username                        : mecid8
twitter_username                          : mecid
github_username                           : mecid
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Heart Rate Points
    description                           : Track your daily heart points to keep your heart healthy.
    fontawesome_icon_name                 : walking
    
  - title                                 : Daily Heart Rate
    description                           : CardioBot presents daily Heart Rate summary chart based on your HR zones.
    fontawesome_icon_name                 : heartbeat
    
  - title                                 : Blood Oxygen
    description                           : CardioBot presents Blood Oxygen analysis. The very important metric during COVID-19 pandemic.
    fontawesome_icon_name                 : brain

  - title                                 : Heart Rate Variability
    description                           : CardioBot calculates your Heart Rate Variability baseline/trend during the 40 days, and show you daily sample analysis.
    fontawesome_icon_name                 : balance-scale

  - title                                 : Blood Pressure
    description                           : CardioBot provides you Blood and Pulse pressure tracking functionality and medication effectiveness analysiss.
    fontawesome_icon_name                 : stethoscope
    
  - title                                 : Sleep
    description                           : By wearing Apple Watch during the sleep you enable Sleep analysis in CardioBot. It presents your sleep quality and sleep heart rate analysis.
    fontawesome_icon_name                 : bed
  
  - title                                 : Workout
    description                           : CardioBot makes your Heart Rate analysis during workout to calculate your workout quality score.
    fontawesome_icon_name                 : running

  - title                                 : Trends
    description                           : CardioBot enables historical data analysis that helps you to understand how new habits influence your heart.
    fontawesome_icon_name                 : chart-bar

  - title                                 : American Heart Association
    description                           : CardioBot powered by smart recommendation system, which helps you to improve every aspect of your heart using AHA studies.
    fontawesome_icon_name                 : comments

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#FF453A"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#fff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF453A"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#FF453A"
social_icons_background_color             : "#222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
