#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1574121774
ios_app_country                           : us                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Nerd
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : |
    Nerd is the go-to app for students who want quick answers to their toughest questions. With Nerd, students can easily connect with a community of like-minded learners, get real-time answers, and make studying fun. Download Nerd today and start acing your exams!


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Navjeeven Mann
your_link                                 :
your_city                                 : Toronto
email_address                             : jeevendeveloper@gmail.com
facebook_username                         :
instagram_username                        : navjeeven
twitter_username                          : navjeeven
github_username                           : JeevenMann
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ask a Question
    description                           : Easily post your toughest questions to the Nerd community and get answers from other students in real-time.
    fontawesome_icon_name                 : question
    
  - title                                 : Answer a Question
    description                           : Help your fellow students by answering their questions and sharing your knowledge.
    fontawesome_icon_name                 : lightbulb
    
  - title                                 : Connect with Like-minded Learners
    description                           : Connect with other students who share your interests and passion for learning.
    fontawesome_icon_name                 : user-group

  - title                                 : Secure Data Storage
    description                           : Rest easy knowing that your personal information is kept secure through our secure data storage system.
    fontawesome_icon_name                 : lock
    
  - title                                 : User Privacy
    description                           : We value your privacy and will never sell or share your personal information with third parties.
    fontawesome_icon_name                 : eye-slash
    
  - title                                 : User-friendly Interface
    description                           : Our intuitive interface makes it easy for students of all ages and backgrounds to use Nerd and get the most out of their learning experience.
    fontawesome_icon_name                 : uikit
  



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#0066FF"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#fff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0066FF"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#0066FF"
social_icons_background_color             : "#222"

footer_text_color                         : "#222"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
